//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Analysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalysisResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalysisResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Analysis.AnalysisResources", typeof(AnalysisResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimatedKnownPhraseCounts.
        /// </summary>
        public static string AnalysisIdEstimatedKnownPhraseCounts {
            get {
                return ResourceManager.GetString("AnalysisIdEstimatedKnownPhraseCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string BeliefStrengthKnownAll {
            get {
                return ResourceManager.GetString("BeliefStrengthKnownAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .75.
        /// </summary>
        public static string BeliefStrengthKnownMost {
            get {
                return ResourceManager.GetString("BeliefStrengthKnownMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .01.
        /// </summary>
        public static string BeliefStrengthKnownNone {
            get {
                return ResourceManager.GetString("BeliefStrengthKnownNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .25.
        /// </summary>
        public static string BeliefStrengthKnownSome {
            get {
                return ResourceManager.GetString("BeliefStrengthKnownSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis type ({0}) or id ({1}) is not recognized..
        /// </summary>
        public static string ErrorMsgAnalysisNotRecognizedException {
            get {
                return ResourceManager.GetString("ErrorMsgAnalysisNotRecognizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B41422B7-602D-4C50-8593-45DF8EB1FAB8.
        /// </summary>
        public static string IdSimplePhraseBeliefAnalyzer {
            get {
                return ResourceManager.GetString("IdSimplePhraseBeliefAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.7.
        /// </summary>
        public static string MinimumStrengthThresholdForKnowledge {
            get {
                return ResourceManager.GetString("MinimumStrengthThresholdForKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MinNumberOfPhraseBeliefsToInterpolateStrength {
            get {
                return ResourceManager.GetString("MinNumberOfPhraseBeliefsToInterpolateStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        public static string NumberOfPhrasesPerRefinement {
            get {
                return ResourceManager.GetString("NumberOfPhrasesPerRefinement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        public static string TimeToSleepIfRefinedCompletelyInMs {
            get {
                return ResourceManager.GetString("TimeToSleepIfRefinedCompletelyInMs", resourceCulture);
            }
        }
    }
}
