//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Mvc4 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mvc4Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mvc4Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Mvc4.Mvc4Resources", typeof(Mvc4Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ActionNameAbout {
            get {
                return ResourceManager.GetString("ActionNameAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ActionNameContact {
            get {
                return ResourceManager.GetString("ActionNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string ActionNameHome {
            get {
                return ResourceManager.GetString("ActionNameHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string ActionNameSilverlightApp {
            get {
                return ResourceManager.GetString("ActionNameSilverlightApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string ActionNameVision {
            get {
                return ResourceManager.GetString("ActionNameVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ControllerNameHome {
            get {
                return ResourceManager.GetString("ControllerNameHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ControllerNameLogin {
            get {
                return ResourceManager.GetString("ControllerNameLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLineTextList.
        /// </summary>
        public static string ControllerNameMultiLineTextListController {
            get {
                return ResourceManager.GetString("ControllerNameMultiLineTextListController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilverlightApp.
        /// </summary>
        public static string ControllerNameSilverlightApp {
            get {
                return ResourceManager.GetString("ControllerNameSilverlightApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string IdentityKey {
            get {
                return ResourceManager.GetString("IdentityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aboutGib.
        /// </summary>
        public static string LinkTextAboutPage {
            get {
                return ResourceManager.GetString("LinkTextAboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibContact.
        /// </summary>
        public static string LinkTextContactPage {
            get {
                return ResourceManager.GetString("LinkTextContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibHome.
        /// </summary>
        public static string LinkTextHomePage {
            get {
                return ResourceManager.GetString("LinkTextHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appGib.
        /// </summary>
        public static string LinkTextSLAppPage {
            get {
                return ResourceManager.GetString("LinkTextSLAppPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibVision.
        /// </summary>
        public static string LinkTextVisionPage {
            get {
                return ResourceManager.GetString("LinkTextVisionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _NavPartial.
        /// </summary>
        public static string PartialNameNav {
            get {
                return ResourceManager.GetString("PartialNameNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Scripts/custom_bundle.
        /// </summary>
        public static string ScriptVirtualPathCustom {
            get {
                return ResourceManager.GetString("ScriptVirtualPathCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Scripts/jquery_bundle.
        /// </summary>
        public static string ScriptVirtualPathJQuery {
            get {
                return ResourceManager.GetString("ScriptVirtualPathJQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Scripts/jquerymobile_bundle.
        /// </summary>
        public static string ScriptVirtualPathJQueryMobile {
            get {
                return ResourceManager.GetString("ScriptVirtualPathJQueryMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Scripts/jqueryui_bundle.
        /// </summary>
        public static string ScriptVirtualPathJQueryUi {
            get {
                return ResourceManager.GetString("ScriptVirtualPathJQueryUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Scripts/jqueryval_bundle.
        /// </summary>
        public static string ScriptVirtualPathJQueryVal {
            get {
                return ResourceManager.GetString("ScriptVirtualPathJQueryVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Scripts/modernizr_bundle.
        /// </summary>
        public static string ScriptVirtualPathModernizr {
            get {
                return ResourceManager.GetString("ScriptVirtualPathModernizr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/mobilecss.
        /// </summary>
        public static string StyleVirtualPathJQueryMobile {
            get {
                return ResourceManager.GetString("StyleVirtualPathJQueryMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/themes/base/css.
        /// </summary>
        public static string StyleVirtualPathJQueryUi {
            get {
                return ResourceManager.GetString("StyleVirtualPathJQueryUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css.
        /// </summary>
        public static string StyleVirtualPathSite {
            get {
                return ResourceManager.GetString("StyleVirtualPathSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aboutGib.
        /// </summary>
        public static string TitleAboutPage {
            get {
                return ResourceManager.GetString("TitleAboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibContact.
        /// </summary>
        public static string TitleContactPage {
            get {
                return ResourceManager.GetString("TitleContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibHome.
        /// </summary>
        public static string TitleHomePage {
            get {
                return ResourceManager.GetString("TitleHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLoginPage {
            get {
                return ResourceManager.GetString("TitleLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appGib.
        /// </summary>
        public static string TitleSLAppPage {
            get {
                return ResourceManager.GetString("TitleSLAppPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibVision.
        /// </summary>
        public static string TitleVisionPage {
            get {
                return ResourceManager.GetString("TitleVisionPage", resourceCulture);
            }
        }
    }
}
