//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Silverlight.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Silverlight.Common.ViewViewModelResources", typeof(ViewViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AutoTitlePrefix {
            get {
                return ResourceManager.GetString("AutoTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DefaultPercentKnown {
            get {
                return ResourceManager.GetString("DefaultPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account settings page is where the user can change any profile information, as well as change passwords and other contact information..
        /// </summary>
        public static string DescriptionAccountSettingsPage {
            get {
                return ResourceManager.GetString("DescriptionAccountSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new song in whatever language you want..
        /// </summary>
        public static string DescriptionAddSongPage {
            get {
                return ResourceManager.GetString("DescriptionAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your Homeeee Pageeeee!.
        /// </summary>
        public static string DescriptionHomePage {
            get {
                return ResourceManager.GetString("DescriptionHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is where you can login to your account..
        /// </summary>
        public static string DescriptionLoginPage {
            get {
                return ResourceManager.GetString("DescriptionLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out!.
        /// </summary>
        public static string DescriptionLogoutPage {
            get {
                return ResourceManager.GetString("DescriptionLogoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is where you go to add/remove users, reset user passwords, etc..
        /// </summary>
        public static string DescriptionManageUsersPage {
            get {
                return ResourceManager.GetString("DescriptionManageUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username ({0}) could NOT be added..
        /// </summary>
        public static string ErrorMsgAddUserWasUnsuccessful {
            get {
                return ResourceManager.GetString("ErrorMsgAddUserWasUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was NOT changed. Be sure to type in the correct previous password..
        /// </summary>
        public static string ErrorMsgPasswordChangeFailed {
            get {
                return ResourceManager.GetString("ErrorMsgPasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ({0}) could NOT be removed..
        /// </summary>
        public static string ErrorMsgRemoveUserWasUnsuccessful {
            get {
                return ResourceManager.GetString("ErrorMsgRemoveUserWasUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your profile information, change your password..
        /// </summary>
        public static string InstructionsAccountSettingsPage {
            get {
                return ResourceManager.GetString("InstructionsAccountSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Add additional info about the song here.  This is still under construction though!!.
        /// </summary>
        public static string InstructionsAddSongEnterSongAdditionalMetadata {
            get {
                return ResourceManager.GetString("InstructionsAddSongEnterSongAdditionalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the entire lyrics to the song, starting with the name of the song and artist on the first two lines.  If you don&apos;t know these, it&apos;s okay - no big.  Be sure to enter the lyrics line by line as you would want to learn them..
        /// </summary>
        public static string InstructionsAddSongEnterSongText {
            get {
                return ResourceManager.GetString("InstructionsAddSongEnterSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Enter the song&apos;s title here.  If you do not provide one, then the first line will act as the song&apos;s title..
        /// </summary>
        public static string InstructionsAddSongEnterSongTitle {
            get {
                return ResourceManager.GetString("InstructionsAddSongEnterSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a song is extremely easy.  Just select the language the song is in, optionally put in the song title and additional info, and then enter the entire lyrics of the song.  Once you are done, click &quot;Save&quot;.  (Hint: You can also hold the mouse over any control for a tooltip on that control.).
        /// </summary>
        public static string InstructionsAddSongPage {
            get {
                return ResourceManager.GetString("InstructionsAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language of the song.  If it is not in the list, click &quot;Add Language&quot; first, then select the newly added language..
        /// </summary>
        public static string InstructionsAddSongSelectLanguage {
            get {
                return ResourceManager.GetString("InstructionsAddSongSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how much of this phrase do you know in the targeted language.  If you know it completely, select 100%.  If you don&apos;t know it at all, select 0%.  If you know somewhere in between, estimate to the best of your ability how much of the translation  you know in the targeted language..
        /// </summary>
        public static string InstructionsAskHowMuchDoYouKnowResponse {
            get {
                return ResourceManager.GetString("InstructionsAskHowMuchDoYouKnowResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter as much text as you want to learn.  We will divide this into smaller phrases and words as we go.
        ///
        ///(If you want to add a song, however, &quot;Add Song&quot; is recommended for learning line order.).
        /// </summary>
        public static string InstructionsEnterPhrase {
            get {
                return ResourceManager.GetString("InstructionsEnterPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be at home on your Home Page..
        /// </summary>
        public static string InstructionsHomePage {
            get {
                return ResourceManager.GetString("InstructionsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password..
        /// </summary>
        public static string InstructionsLoginPage {
            get {
                return ResourceManager.GetString("InstructionsLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the login button to log back in..
        /// </summary>
        public static string InstructionsLogoutPage {
            get {
                return ResourceManager.GetString("InstructionsLogoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user information and choose save..
        /// </summary>
        public static string InstructionsManageUsersPage {
            get {
                return ResourceManager.GetString("InstructionsManageUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string InstructionsSelectLanguage {
            get {
                return ResourceManager.GetString("InstructionsSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelAcceptPercentKnown {
            get {
                return ResourceManager.GetString("LabelAcceptPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelAddLanguageLanguageText {
            get {
                return ResourceManager.GetString("LabelAddLanguageLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        public static string LabelAddPhraseLanguageText {
            get {
                return ResourceManager.GetString("LabelAddPhraseLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase: .
        /// </summary>
        public static string LabelAddPhrasePhraseText {
            get {
                return ResourceManager.GetString("LabelAddPhrasePhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Language: .
        /// </summary>
        public static string LabelAddSongLanguage {
            get {
                return ResourceManager.GetString("LabelAddSongLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Lyrics: .
        /// </summary>
        public static string LabelAddSongSongText {
            get {
                return ResourceManager.GetString("LabelAddSongSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Title: .
        /// </summary>
        public static string LabelAddSongSongTitle {
            get {
                return ResourceManager.GetString("LabelAddSongSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Text: .
        /// </summary>
        public static string LabelAddSongText {
            get {
                return ResourceManager.GetString("LabelAddSongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSaveButton {
            get {
                return ResourceManager.GetString("LabelSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Info: .
        /// </summary>
        public static string LabelSongAdditionalMetadata {
            get {
                return ResourceManager.GetString("LabelSongAdditionalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string MaxInstructionsWidth {
            get {
                return ResourceManager.GetString("MaxInstructionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string MaxThinkingDots {
            get {
                return ResourceManager.GetString("MaxThinkingDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Username ({0}) was successfully added..
        /// </summary>
        public static string MessageNewUserAdded {
            get {
                return ResourceManager.GetString("MessageNewUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ({0}) was successfully removed..
        /// </summary>
        public static string MessageUserWasRemoved {
            get {
                return ResourceManager.GetString("MessageUserWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user? This will permanently delete ALL data associated with the user..
        /// </summary>
        public static string MsgConfirmDeleteUser {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!!!! This cannot be undone!.
        /// </summary>
        public static string MsgConfirmDeleteUserTitle {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        public static string MsgDeleteUserCanceled {
            get {
                return ResourceManager.GetString("MsgDeleteUserCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out!.
        /// </summary>
        public static string MsgLoggedOut {
            get {
                return ResourceManager.GetString("MsgLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging you out....
        /// </summary>
        public static string MsgLoggingOut {
            get {
                return ResourceManager.GetString("MsgLoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was successfully changed!.
        /// </summary>
        public static string MsgPasswordWasSuccessfullyChanged {
            get {
                return ResourceManager.GetString("MsgPasswordWasSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NavButtonTextLogin {
            get {
                return ResourceManager.GetString("NavButtonTextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string NavButtonTextLogout {
            get {
                return ResourceManager.GetString("NavButtonTextLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string NavSetTextAccountSettings {
            get {
                return ResourceManager.GetString("NavSetTextAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string NavSetTextAddSong {
            get {
                return ResourceManager.GetString("NavSetTextAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string NavSetTextAdmin {
            get {
                return ResourceManager.GetString("NavSetTextAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string NavSetTextGeneral {
            get {
                return ResourceManager.GetString("NavSetTextGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string NavSetTextHome {
            get {
                return ResourceManager.GetString("NavSetTextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string NavTextAccountSettingsPage {
            get {
                return ResourceManager.GetString("NavTextAccountSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Song.
        /// </summary>
        public static string NavTextAddSongPage {
            get {
                return ResourceManager.GetString("NavTextAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavTextHomePage {
            get {
                return ResourceManager.GetString("NavTextHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string NavTextLoginPage {
            get {
                return ResourceManager.GetString("NavTextLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string NavTextLogoutPage {
            get {
                return ResourceManager.GetString("NavTextLogoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string NavTextManageUsersPage {
            get {
                return ResourceManager.GetString("NavTextManageUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string ShowGridLines {
            get {
                return ResourceManager.GetString("ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string ShowInstructions {
            get {
                return ResourceManager.GetString("ShowInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string SortOrderAccountSettingsPage {
            get {
                return ResourceManager.GetString("SortOrderAccountSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SortOrderAddSongPage {
            get {
                return ResourceManager.GetString("SortOrderAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SortOrderHomePage {
            get {
                return ResourceManager.GetString("SortOrderHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SortOrderLoginPage {
            get {
                return ResourceManager.GetString("SortOrderLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        public static string SortOrderLogoutPage {
            get {
                return ResourceManager.GetString("SortOrderLogoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SortOrderManageUsersPage {
            get {
                return ResourceManager.GetString("SortOrderManageUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string TitleAccountSettingsPage {
            get {
                return ResourceManager.GetString("TitleAccountSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Language.
        /// </summary>
        public static string TitleAddLanguage {
            get {
                return ResourceManager.GetString("TitleAddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Song.
        /// </summary>
        public static string TitleAddSongPage {
            get {
                return ResourceManager.GetString("TitleAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHomePage {
            get {
                return ResourceManager.GetString("TitleHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLoginPage {
            get {
                return ResourceManager.GetString("TitleLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Out.
        /// </summary>
        public static string TitleLogoutPage {
            get {
                return ResourceManager.GetString("TitleLogoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin: Manage Users.
        /// </summary>
        public static string TitleManageUsersPage {
            get {
                return ResourceManager.GetString("TitleManageUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account information. Change your password..
        /// </summary>
        public static string ToolTipAccountSettingsPage {
            get {
                return ResourceManager.GetString("ToolTipAccountSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the song in the box, line by line..
        /// </summary>
        public static string ToolTipAddSongPage {
            get {
                return ResourceManager.GetString("ToolTipAddSongPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Home!.
        /// </summary>
        public static string ToolTipHomePage {
            get {
                return ResourceManager.GetString("ToolTipHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password..
        /// </summary>
        public static string ToolTipLoginPage {
            get {
                return ResourceManager.GetString("ToolTipLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the login button to log back in..
        /// </summary>
        public static string ToolTipLogoutPage {
            get {
                return ResourceManager.GetString("ToolTipLogoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the users well!.
        /// </summary>
        public static string ToolTipManageUsersPage {
            get {
                return ResourceManager.GetString("ToolTipManageUsersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Language.
        /// </summary>
        public static string ToolTipTextAddLanguage {
            get {
                return ResourceManager.GetString("ToolTipTextAddLanguage", resourceCulture);
            }
        }
    }
}
