//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Silverlight {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Silverlight.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me how much of this phrase you know..
        /// </summary>
        public static string AskDoYouKnowThisInstructionsText {
            get {
                return ResourceManager.GetString("AskDoYouKnowThisInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:50094/.
        /// </summary>
        public static string BaseAddress {
            get {
                return ResourceManager.GetString("BaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A8D01FD8-7937-4675-A098-2437E193F2EA.
        /// </summary>
        public static string ClientIdRegisteredWithAzureMarketplace {
            get {
                return ResourceManager.GetString("ClientIdRegisteredWithAzureMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Translation Phrases.
        /// </summary>
        public static string DefaultAddTranslationPhrasesViewModelToolTip {
            get {
                return ResourceManager.GetString("DefaultAddTranslationPhrasesViewModelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn Languages!.
        /// </summary>
        public static string DefaultAppTitle {
            get {
                return ResourceManager.GetString("DefaultAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewStudyDataNativeLanguageText {
            get {
                return ResourceManager.GetString("DefaultNewStudyDataNativeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phrase is awesome -  I want to translate it into sooooo many languages!.
        /// </summary>
        public static string DefaultStudyPhrase {
            get {
                return ResourceManager.GetString("DefaultStudyPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string EnglishLanguageCode {
            get {
                return ResourceManager.GetString("EnglishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishLanguageText {
            get {
                return ResourceManager.GetString("EnglishLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer is null..
        /// </summary>
        public static string ErrorMsgAnswerIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgAnswerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is null..
        /// </summary>
        public static string ErrorMsgLanguageIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Language.Text is null or empty..
        /// </summary>
        public static string ErrorMsgLanguageTextIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is null..
        /// </summary>
        public static string ErrorMsgQuestionIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgQuestionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to use auto-translation service, but it is not available at this time.  Causes of this may include: The service could be down, there could be a cross domain policy issue, the internet connection might be down, or the firewall could be blocking the service..
        /// </summary>
        public static string ErrorMsgTranslateServiceNotAvailable {
            get {
                return ResourceManager.GetString("ErrorMsgTranslateServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login incorrect.  Please wait a moment and then try again..
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4000.
        /// </summary>
        public static string LoginFailedPenaltyInMilliseconds {
            get {
                return ResourceManager.GetString("LoginFailedPenaltyInMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged out...Come back soon!.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MinNativeLanguageTextLength {
            get {
                return ResourceManager.GetString("MinNativeLanguageTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string MinUsernameLength {
            get {
                return ResourceManager.GetString("MinUsernameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string ShowGridLines {
            get {
                return ResourceManager.GetString("ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string SpanishLanguageCode {
            get {
                return ResourceManager.GetString("SpanishLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SpanishLanguageText {
            get {
                return ResourceManager.GetString("SpanishLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Complete!.
        /// </summary>
        public static string StudyCompletedMessage {
            get {
                return ResourceManager.GetString("StudyCompletedMessage", resourceCulture);
            }
        }
    }
}
