//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Study {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Study.StudyResources", typeof(StudyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEE32EE6-6411-49BB-8A27-DD1C472E21B9.
        /// </summary>
        public static string AdvisorIdPhrasePercentKnownStudyAdvisor {
            get {
                return ResourceManager.GetString("AdvisorIdPhrasePercentKnownStudyAdvisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the percent known of this phrase?.
        /// </summary>
        public static string AdvisorQuestionWhatIsPhrasePercentKnown {
            get {
                return ResourceManager.GetString("AdvisorQuestionWhatIsPhrasePercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string AutoSavePhrasesAutomaticallyTranslated {
            get {
                return ResourceManager.GetString("AutoSavePhrasesAutomaticallyTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string BeliefTextKeyValueEntrySeparator {
            get {
                return ResourceManager.GetString("BeliefTextKeyValueEntrySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string BeliefTextKeyValueEqualityOperator {
            get {
                return ResourceManager.GetString("BeliefTextKeyValueEqualityOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string BeliefTextPrefix {
            get {
                return ResourceManager.GetString("BeliefTextPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A71DCFCC34133403B25C909D017FE0B140799549.
        /// </summary>
        public static string BingAppId {
            get {
                return ResourceManager.GetString("BingAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinkin&apos; hard bout that data!.
        /// </summary>
        public static string BusyContentSimpleProgressPageInitializingData {
            get {
                return ResourceManager.GetString("BusyContentSimpleProgressPageInitializingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ButtonLabelApplyFilter {
            get {
                return ResourceManager.GetString("ButtonLabelApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ButtonLabelEdit {
            get {
                return ResourceManager.GetString("ButtonLabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string ButtonLabelResearchAnswer {
            get {
                return ResourceManager.GetString("ButtonLabelResearchAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string ButtonLabelResearchQuestion {
            get {
                return ResourceManager.GetString("ButtonLabelResearchQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonLabelSave {
            get {
                return ResourceManager.GetString("ButtonLabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Answer.
        /// </summary>
        public static string ButtonLabelShowAnswer {
            get {
                return ResourceManager.GetString("ButtonLabelShowAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string ButtonLabelStudySongsGo {
            get {
                return ResourceManager.GetString("ButtonLabelStudySongsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string CategoryStudy {
            get {
                return ResourceManager.GetString("CategoryStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Learned (appx.).
        /// </summary>
        public static string ChartTitleSimpleProgress {
            get {
                return ResourceManager.GetString("ChartTitleSimpleProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000.
        /// </summary>
        public static string DefaultAmountDefaultMultiLineTextsStudier {
            get {
                return ResourceManager.GetString("DefaultAmountDefaultMultiLineTextsStudier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string DefaultAmountDefaultPhraseMeaningStudier {
            get {
                return ResourceManager.GetString("DefaultAmountDefaultPhraseMeaningStudier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string DefaultBeliefStrength {
            get {
                return ResourceManager.GetString("DefaultBeliefStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90.
        /// </summary>
        public static string DefaultExpectedPrecision {
            get {
                return ResourceManager.GetString("DefaultExpectedPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string DefaultFeedbackCheckIntervalMilliseconds {
            get {
                return ResourceManager.GetString("DefaultFeedbackCheckIntervalMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300000.
        /// </summary>
        public static string DefaultFeedbackTimeoutMilliseconds {
            get {
                return ResourceManager.GetString("DefaultFeedbackTimeoutMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .85.
        /// </summary>
        public static string DefaultKnowledgeThreshold {
            get {
                return ResourceManager.GetString("DefaultKnowledgeThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string DefaultMaxIterationsAggregateAdjacentKnownPhraseTexts {
            get {
                return ResourceManager.GetString("DefaultMaxIterationsAggregateAdjacentKnownPhraseTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string DefaultMeaningStudierActiveLinesCount {
            get {
                return ResourceManager.GetString("DefaultMeaningStudierActiveLinesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string DefaultMeaningStudierAggregateSize {
            get {
                return ResourceManager.GetString("DefaultMeaningStudierAggregateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string DefaultMillisecondsTimePerWordInQuestion {
            get {
                return ResourceManager.GetString("DefaultMillisecondsTimePerWordInQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string DefaultMultiLineTextsStudierMeaningWeight {
            get {
                return ResourceManager.GetString("DefaultMultiLineTextsStudierMeaningWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string DefaultMultiLineTextsStudierOrderWeight {
            get {
                return ResourceManager.GetString("DefaultMultiLineTextsStudierOrderWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92A7E7C6-8278-4142-A962-6616E2959D1C.
        /// </summary>
        public static string DefaultOfferExchangeId {
            get {
                return ResourceManager.GetString("DefaultOfferExchangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string DefaultOrderStudierLineGroupSize {
            get {
                return ResourceManager.GetString("DefaultOrderStudierLineGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4F8FA6A7-DD12-4A32-A3C6-FF248059926B.
        /// </summary>
        public static string DefaultPhraseAutoTranslatedRecorderId {
            get {
                return ResourceManager.GetString("DefaultPhraseAutoTranslatedRecorderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8FA20DFF-0C65-4BC0-B4AC-38B72AB03CD7.
        /// </summary>
        public static string DefaultPhraseReviewedRecorderId {
            get {
                return ResourceManager.GetString("DefaultPhraseReviewedRecorderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string DefaultStudyHeartbeatTimeMilliseconds {
            get {
                return ResourceManager.GetString("DefaultStudyHeartbeatTimeMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Ya ya ya!.
        /// </summary>
        public static string DefaultStudyTitle {
            get {
                return ResourceManager.GetString("DefaultStudyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DefaultThinkAboutAnswerTime {
            get {
                return ResourceManager.GetString("DefaultThinkAboutAnswerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string DefaultTimeLineOrderQuestionInMilliseconds {
            get {
                return ResourceManager.GetString("DefaultTimeLineOrderQuestionInMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string DefaultTimeoutGetPercentKnown {
            get {
                return ResourceManager.GetString("DefaultTimeoutGetPercentKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73A27EAD-A83E-4FBA-B400-679A1AC58AC7.
        /// </summary>
        public static string DefaultWordInPhraseReviewedRecorderId {
            get {
                return ResourceManager.GetString("DefaultWordInPhraseReviewedRecorderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study here, study there, this is a description of how to study everywhere..
        /// </summary>
        public static string DescriptionExecuteStudySongsPage {
            get {
                return ResourceManager.GetString("DescriptionExecuteStudySongsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows your awesome progress what-do-you-know!.
        /// </summary>
        public static string DescriptionSimpleProgressPage {
            get {
                return ResourceManager.GetString("DescriptionSimpleProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can study multiple songs in both your native language and foreign languages as well!.
        /// </summary>
        public static string DescriptionStudyASongViewModel {
            get {
                return ResourceManager.GetString("DescriptionStudyASongViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is for studying a bunch of stuff and whatnot how-do-you-do..
        /// </summary>
        public static string DescriptionStudyStuffPage {
            get {
                return ResourceManager.GetString("DescriptionStudyStuffPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer is null..
        /// </summary>
        public static string ErrorMsgAnswerIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgAnswerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when getting the next study item. ({0}).
        /// </summary>
        public static string ErrorMsgGetNextStudyItemViewModel {
            get {
                return ResourceManager.GetString("ErrorMsgGetNextStudyItemViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when getting an random unknown phrase..
        /// </summary>
        public static string ErrorMsgGetRandomUnknownPhrase {
            get {
                return ResourceManager.GetString("ErrorMsgGetRandomUnknownPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when initializing for new study session. ({0}).
        /// </summary>
        public static string ErrorMsgInitializeForNewStudySession {
            get {
                return ResourceManager.GetString("ErrorMsgInitializeForNewStudySession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is null..
        /// </summary>
        public static string ErrorMsgLanguageIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Language.Text is null or empty..
        /// </summary>
        public static string ErrorMsgLanguageTextIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question is null..
        /// </summary>
        public static string ErrorMsgQuestionIsNull {
            get {
                return ResourceManager.GetString("ErrorMsgQuestionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs that could not be deleted: {0}.
        /// </summary>
        public static string ErrorMsgSomeSongsWereNotDeletedDetailed {
            get {
                return ResourceManager.GetString("ErrorMsgSomeSongsWereNotDeletedDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some songs could not be deleted. This has been logged..
        /// </summary>
        public static string ErrorMsgSomeSongsWereNotDeletedSimple {
            get {
                return ResourceManager.GetString("ErrorMsgSomeSongsWereNotDeletedSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown during study.  See inner exception for details..
        /// </summary>
        public static string ErrorMsgStudyException {
            get {
                return ResourceManager.GetString("ErrorMsgStudyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your native language.  This is the language you feel most comfortable with, usually the one you grew up speaking the most..
        /// </summary>
        public static string InstructionsAskUserExtraData {
            get {
                return ResourceManager.GetString("InstructionsAskUserExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your native language.  This is the language you feel most comfortable with, usually the one you grew up speaking the most..
        /// </summary>
        public static string InstructionsAskUserExtraDataSelectNativeLanguageText {
            get {
                return ResourceManager.GetString("InstructionsAskUserExtraDataSelectNativeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue learning, click Next.  Choose your feedback.  More instructions here......
        /// </summary>
        public static string InstructionsDefaultStudyPartner {
            get {
                return ResourceManager.GetString("InstructionsDefaultStudyPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are generic study instructions..
        /// </summary>
        public static string InstructionsExecuteStudySongsPage {
            get {
                return ResourceManager.GetString("InstructionsExecuteStudySongsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know this item completely. (95%-100%).
        /// </summary>
        public static string InstructionsSelectFeedbackAll {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know the majority of this item.  (50%-95%).
        /// </summary>
        public static string InstructionsSelectFeedbackMost {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hardly know this item at all.  (0%-5%).
        /// </summary>
        public static string InstructionsSelectFeedbackNone {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the amount of knowledge you have of the given item.  Approximate to the best of your ability!.
        /// </summary>
        public static string InstructionsSelectFeedbackNoneSomeMostAll {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackNoneSomeMostAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know a little, or even perhaps, a decent amount of this item. (5%-50%).
        /// </summary>
        public static string InstructionsSelectFeedbackSome {
            get {
                return ResourceManager.GetString("InstructionsSelectFeedbackSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a single song or multiple songs..
        /// </summary>
        public static string InstructionsSelectSongsSelectSong {
            get {
                return ResourceManager.GetString("InstructionsSelectSongsSelectSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the song(s) that you want to study...Once selected, press Go!.
        /// </summary>
        public static string InstructionsStudySongsSelectSong {
            get {
                return ResourceManager.GetString("InstructionsStudySongsSelectSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Some Stuff Don&apos;tcha Know.
        /// </summary>
        public static string InstructionsStudyStuff {
            get {
                return ResourceManager.GetString("InstructionsStudyStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Native Language: .
        /// </summary>
        public static string LabelAskUserExtraDataNativeLanguageText {
            get {
                return ResourceManager.GetString("LabelAskUserExtraDataNativeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Native Language: .
        /// </summary>
        public static string LabelSelectNativeLanguageLanguageText {
            get {
                return ResourceManager.GetString("LabelSelectNativeLanguageLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string LabelStudySongsFilter {
            get {
                return ResourceManager.GetString("LabelStudySongsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        public static string MaxTriesToPickRandomFromEntireList {
            get {
                return ResourceManager.GetString("MaxTriesToPickRandomFromEntireList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The songs were successfully deleted..
        /// </summary>
        public static string MsgSongsSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("MsgSongsSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string NavSetTextLanguages {
            get {
                return ResourceManager.GetString("NavSetTextLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string NavTextSimpleProgressPage {
            get {
                return ResourceManager.GetString("NavTextSimpleProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Songs.
        /// </summary>
        public static string NavTextStudySongs {
            get {
                return ResourceManager.GetString("NavTextStudySongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string PercentKnownAll {
            get {
                return ResourceManager.GetString("PercentKnownAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .75.
        /// </summary>
        public static string PercentKnownMost {
            get {
                return ResourceManager.GetString("PercentKnownMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .01.
        /// </summary>
        public static string PercentKnownNone {
            get {
                return ResourceManager.GetString("PercentKnownNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .25.
        /// </summary>
        public static string PercentKnownSome {
            get {
                return ResourceManager.GetString("PercentKnownSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1.
        /// </summary>
        public static string ProbabilityChooseMeaningIfKnowAllOfMeaning {
            get {
                return ResourceManager.GetString("ProbabilityChooseMeaningIfKnowAllOfMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.8.
        /// </summary>
        public static string ProbabilityChooseMeaningIfKnowMostOfMeaning {
            get {
                return ResourceManager.GetString("ProbabilityChooseMeaningIfKnowMostOfMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.9.
        /// </summary>
        public static string ProbabilityChooseMeaningIfKnowSomeOfMeaning {
            get {
                return ResourceManager.GetString("ProbabilityChooseMeaningIfKnowSomeOfMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 67B84750-AA2A-4EE8-B817-56183FD56CDE.
        /// </summary>
        public static string RecorderIdReviewedPhrase {
            get {
                return ResourceManager.GetString("RecorderIdReviewedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.bing.com/?q=translate {0}.
        /// </summary>
        public static string ResearchFormatStringBing {
            get {
                return ResourceManager.GetString("ResearchFormatStringBing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.google.com/?q=translate {0}.
        /// </summary>
        public static string ResearchFormatStringGoogle {
            get {
                return ResourceManager.GetString("ResearchFormatStringGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2DF2AF17-CE4E-462B-AD39-B6E31DF985A5.
        /// </summary>
        public static string ReviewMethodIdDefaultPhraseMeaningStudier {
            get {
                return ResourceManager.GetString("ReviewMethodIdDefaultPhraseMeaningStudier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360BF760-95AA-4EB3-B2E2-C7DAD1EB29AA.
        /// </summary>
        public static string ReviewMethodIdStudyLineOrderManualQA {
            get {
                return ResourceManager.GetString("ReviewMethodIdStudyLineOrderManualQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0DB35AFA-49A9-4C11-A4B1-B4C6795B5931.
        /// </summary>
        public static string ReviewMethodIdStudyLineOrderTimedQA {
            get {
                return ResourceManager.GetString("ReviewMethodIdStudyLineOrderTimedQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E5F6AF74-2F9D-4067-921B-009DE109759D.
        /// </summary>
        public static string ReviewMethodIdStudyPhraseManualQA {
            get {
                return ResourceManager.GetString("ReviewMethodIdStudyPhraseManualQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C7061A4F-43A1-4F31-B40D-4B6F5B8020A7.
        /// </summary>
        public static string ReviewMethodIdStudyPhraseTimedQA {
            get {
                return ResourceManager.GetString("ReviewMethodIdStudyPhraseTimedQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string ShowGridLines {
            get {
                return ResourceManager.GetString("ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string ShowInstructions {
            get {
                return ResourceManager.GetString("ShowInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string SortOrderSimpleProgressPage {
            get {
                return ResourceManager.GetString("SortOrderSimpleProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        public static string SortOrderStudySongs {
            get {
                return ResourceManager.GetString("SortOrderStudySongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string SourceNameDatabase {
            get {
                return ResourceManager.GetString("SourceNameDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string StudyContextMeaning {
            get {
                return ResourceManager.GetString("StudyContextMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string StudyContextOrder {
            get {
                return ResourceManager.GetString("StudyContextOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string StudyContextTotal {
            get {
                return ResourceManager.GetString("StudyContextTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the next line?.
        /// </summary>
        public static string StudyLineManualQuestionAnswerStudyItemTitle {
            get {
                return ResourceManager.GetString("StudyLineManualQuestionAnswerStudyItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudyLineOrderAnswerHeader {
            get {
                return ResourceManager.GetString("StudyLineOrderAnswerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line # .
        /// </summary>
        public static string StudyLineOrderLineNumberPrefix {
            get {
                return ResourceManager.GetString("StudyLineOrderLineNumberPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _____.
        /// </summary>
        public static string StudyLineOrderQuestionBlank {
            get {
                return ResourceManager.GetString("StudyLineOrderQuestionBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number: {0}.
        /// </summary>
        public static string StudyLineOrderQuestionHeader {
            get {
                return ResourceManager.GetString("StudyLineOrderQuestionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the first line?.
        /// </summary>
        public static string StudyLineOrderQuestionWhatIsFirstLine {
            get {
                return ResourceManager.GetString("StudyLineOrderQuestionWhatIsFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        public static string StudyLineOrderSeparatorBetweenLineNumberAndLineText {
            get {
                return ResourceManager.GetString("StudyLineOrderSeparatorBetweenLineNumberAndLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the next line?.
        /// </summary>
        public static string StudyLineTimedQuestionAnswerStudyItemTitle {
            get {
                return ResourceManager.GetString("StudyLineTimedQuestionAnswerStudyItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate this phrase..
        /// </summary>
        public static string StudyPhraseManualQuestionAnswerStudyItemTitle {
            get {
                return ResourceManager.GetString("StudyPhraseManualQuestionAnswerStudyItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate this phrase..
        /// </summary>
        public static string StudyPhraseTimedQuestionAnswerStudyItemTitle {
            get {
                return ResourceManager.GetString("StudyPhraseTimedQuestionAnswerStudyItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study.
        /// </summary>
        public static string TitleExecuteStudySongsPage {
            get {
                return ResourceManager.GetString("TitleExecuteStudySongsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string TitleSimpleProgressPage {
            get {
                return ResourceManager.GetString("TitleSimpleProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Song(s).
        /// </summary>
        public static string TitleStudySongsViewModel {
            get {
                return ResourceManager.GetString("TitleStudySongsViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study them songs yo!.
        /// </summary>
        public static string ToolTipExecuteStudySongsPage {
            get {
                return ResourceManager.GetString("ToolTipExecuteStudySongsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a single song or multiple songs..
        /// </summary>
        public static string ToolTipSelectSongs {
            get {
                return ResourceManager.GetString("ToolTipSelectSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page shows your awesome progress what-do-you-know!.
        /// </summary>
        public static string ToolTipSimpleProgressPage {
            get {
                return ResourceManager.GetString("ToolTipSimpleProgressPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study songs yo!.
        /// </summary>
        public static string ToolTipStudySongs {
            get {
                return ResourceManager.GetString("ToolTipStudySongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty phrase text was found in AggregatePhraseTexts.  This shouldn&apos;t happen..
        /// </summary>
        public static string WarningMsgEmptyAggregatePhraseTextFound {
            get {
                return ResourceManager.GetString("WarningMsgEmptyAggregatePhraseTextFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown offer response ({0}) was given..
        /// </summary>
        public static string WarningMsgUnknownOfferResponseResponse {
            get {
                return ResourceManager.GetString("WarningMsgUnknownOfferResponseResponse", resourceCulture);
            }
        }
    }
}
