//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Autonomous {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceManagerConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceManagerConfigurationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Autonomous.ServiceManagerConfigurationResources", typeof(ServiceManagerConfigurationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DefaultConcurrentContexts {
            get {
                return ResourceManager.GetString("DefaultConcurrentContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string DefaultContextAllowedAbortTimeInMs {
            get {
                return ResourceManager.GetString("DefaultContextAllowedAbortTimeInMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60000.
        /// </summary>
        internal static string DefaultContextAllowedExecuteTimeInMs {
            get {
                return ResourceManager.GetString("DefaultContextAllowedExecuteTimeInMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string DefaultContextAllowedLoadTimeInMs {
            get {
                return ResourceManager.GetString("DefaultContextAllowedLoadTimeInMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string DefaultContextRandomSalt {
            get {
                return ResourceManager.GetString("DefaultContextRandomSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string DefaultKillAllContextsAllowedTimeInMs {
            get {
                return ResourceManager.GetString("DefaultKillAllContextsAllowedTimeInMs", resourceCulture);
            }
        }
    }
}
