//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.Business.BusinessResources", typeof(BusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewStudyDataNativeLanguageText {
            get {
                return ResourceManager.GetString("DefaultNewStudyDataNativeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        public static string DefaultPhraseBeliefStrength {
            get {
                return ResourceManager.GetString("DefaultPhraseBeliefStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultPhraseBeliefText {
            get {
                return ResourceManager.GetString("DefaultPhraseBeliefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string MetadataEquals {
            get {
                return ResourceManager.GetString("MetadataEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MetadataKeyType {
            get {
                return ResourceManager.GetString("MetadataKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        public static string MetadataSeparator {
            get {
                return ResourceManager.GetString("MetadataSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poem.
        /// </summary>
        public static string MetadataValueTypePoem {
            get {
                return ResourceManager.GetString("MetadataValueTypePoem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string MetadataValueTypeSong {
            get {
                return ResourceManager.GetString("MetadataValueTypeSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MinNativeLanguageTextLength {
            get {
                return ResourceManager.GetString("MinNativeLanguageTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.Count must equal {1}.Count.
        /// </summary>
        public static string RuleInfoCountsMustBeEqual {
            get {
                return ResourceManager.GetString("RuleInfoCountsMustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum count of {0} is {1}..
        /// </summary>
        public static string RuleInfoMinimumCount {
            get {
                return ResourceManager.GetString("RuleInfoMinimumCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||.
        /// </summary>
        public static string SettingsStringSeparator {
            get {
                return ResourceManager.GetString("SettingsStringSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string SongMinimumLineCount {
            get {
                return ResourceManager.GetString("SongMinimumLineCount", resourceCulture);
            }
        }
    }
}
