//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnLanguages.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnLanguages.DataAccess.DalResources", typeof(DalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllPhrasesList_DalKey.
        /// </summary>
        public static string AllPhrasesList_DalKey {
            get {
                return ResourceManager.GetString("AllPhrasesList_DalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DalManagerType.
        /// </summary>
        public static string AppSettingsKeyDalManagerTypeName {
            get {
                return ResourceManager.GetString("AppSettingsKeyDalManagerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string AuthenticationTypeString {
            get {
                return ResourceManager.GetString("AuthenticationTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DalSeedDataInitializedKey.
        /// </summary>
        public static string DalSeedDataInitializedKey {
            get {
                return ResourceManager.GetString("DalSeedDataInitializedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10D85B4-4DE4-40CB-8ABD-9458AD9B7FD9.
        /// </summary>
        public static string DefaultEnglishLanguageId {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string DefaultEnglishLanguageText {
            get {
                return ResourceManager.GetString("DefaultEnglishLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C10D85B4-4DE4-40CB-8ABD-9458AD9B7FD9.
        /// </summary>
        public static string DefaultLanguageId {
            get {
                return ResourceManager.GetString("DefaultLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        public static string DefaultLineNumber {
            get {
                return ResourceManager.GetString("DefaultLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultMultiLineTextAdditionalMetadata {
            get {
                return ResourceManager.GetString("DefaultMultiLineTextAdditionalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNativeLanguageText {
            get {
                return ResourceManager.GetString("DefaultNativeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewArtistName {
            get {
                return ResourceManager.GetString("DefaultNewArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewLanguageText {
            get {
                return ResourceManager.GetString("DefaultNewLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewLineUsername {
            get {
                return ResourceManager.GetString("DefaultNewLineUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewMultiLineTextAdditionalMetadata {
            get {
                return ResourceManager.GetString("DefaultNewMultiLineTextAdditionalMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewMultiLineTextTitle {
            get {
                return ResourceManager.GetString("DefaultNewMultiLineTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewMultiLineTextUsername {
            get {
                return ResourceManager.GetString("DefaultNewMultiLineTextUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string DefaultNewPhraseBeliefStrength {
            get {
                return ResourceManager.GetString("DefaultNewPhraseBeliefStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewPhraseBeliefText {
            get {
                return ResourceManager.GetString("DefaultNewPhraseBeliefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewPhraseText {
            get {
                return ResourceManager.GetString("DefaultNewPhraseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewPhraseUsername {
            get {
                return ResourceManager.GetString("DefaultNewPhraseUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultNewTranslationUsername {
            get {
                return ResourceManager.GetString("DefaultNewTranslationUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DefaultUsername {
            get {
                return ResourceManager.GetString("DefaultUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to add the user with username ({0})..
        /// </summary>
        public static string ErrorMsgAddUserFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgAddUserFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to add user..
        /// </summary>
        public static string ErrorMsgAttemptedToAddUser {
            get {
                return ResourceManager.GetString("ErrorMsgAttemptedToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to delete user..
        /// </summary>
        public static string ErrorMsgAttemptedToDeleteUser {
            get {
                return ResourceManager.GetString("ErrorMsgAttemptedToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to get all users..
        /// </summary>
        public static string ErrorMsgAttemptedToGetAllUsers {
            get {
                return ResourceManager.GetString("ErrorMsgAttemptedToGetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The criteria given was incorrect.  The expected criteria is as follows: {0}.
        /// </summary>
        public static string ErrorMsgBadCriteriaException {
            get {
                return ResourceManager.GetString("ErrorMsgBadCriteriaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria is expected to be of type UserDto.
        /// </summary>
        public static string ErrorMsgBadCriteriaExceptionDetail_ExpectedTypeIsUserDto {
            get {
                return ResourceManager.GetString("ErrorMsgBadCriteriaExceptionDetail_ExpectedTypeIsUserDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to change the password..
        /// </summary>
        public static string ErrorMsgChangePasswordFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgChangePasswordFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Create operation failed. InnerExceptionMsg = {0}.
        /// </summary>
        public static string ErrorMsgCreateFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgCreateFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when manipulating the database..
        /// </summary>
        public static string ErrorMsgDatabaseException {
            get {
                return ResourceManager.GetString("ErrorMsgDatabaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed. InnerExceptionMsg = {0}.
        /// </summary>
        public static string ErrorMsgDeleteFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgDeleteFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Delete operation failed.  There were multiple items found to delete..
        /// </summary>
        public static string ErrorMsgDeleteFailedExceptionDetail_MultipleItemsFound {
            get {
                return ResourceManager.GetString("ErrorMsgDeleteFailedExceptionDetail_MultipleItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fetch operation failed. InnerExceptionMsg = {0}.
        /// </summary>
        public static string ErrorMsgFetchFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgFetchFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeneralDataAccessException.  InnerExceptionMsg = {0}.
        /// </summary>
        public static string ErrorMsgGeneralDataAccessException {
            get {
                return ResourceManager.GetString("ErrorMsgGeneralDataAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GetAll operation failed. InnerExceptionMsg = {0}.
        /// </summary>
        public static string ErrorMsgGetAllFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgGetAllFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The roles of user ({0}) could not be retrieved. InnerExceptionMsg = {1}.
        /// </summary>
        public static string ErrorMsgGetRolesFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgGetRolesFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUser Failed. Username: ({0}) InnerExceptionMsg = {1}.
        /// </summary>
        public static string ErrorMsgGetUserFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgGetUserFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id ({0}) already exists..
        /// </summary>
        public static string ErrorMsgIdAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorMsgIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id ({0}) already exists..
        /// </summary>
        public static string ErrorMsgIdAlreadyExistsException {
            get {
                return ResourceManager.GetString("ErrorMsgIdAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id ({0}) was not found..
        /// </summary>
        public static string ErrorMsgIdNotFoundException {
            get {
                return ResourceManager.GetString("ErrorMsgIdNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insert operation failed. InnerExceptionMsg = {0}.
        /// </summary>
        public static string ErrorMsgInsertFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgInsertFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password ({0}) is invalid. It must contain at least one digit and one letter (upper or lowercase), and can also include !@#$%^&amp;*() characters..
        /// </summary>
        public static string ErrorMsgInvalidPasswordException {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username ({0}) is invalid. It must contain only letters, numbers, underscore, dash, periods..
        /// </summary>
        public static string ErrorMsgInvalidUsernameException {
            get {
                return ResourceManager.GetString("ErrorMsgInvalidUsernameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Language Text ({0}) already exists..
        /// </summary>
        public static string ErrorMsgLanguageTextAlreadyExistsException {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language ({0}) not found.  Be sure that the spelling and case-sensitivity are correct and that the language has been added..
        /// </summary>
        public static string ErrorMsgLanguageTextNotFoundException {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During a LineList create operation with LineInfosCriteria, there was a problem when trying to fetch/create the languagetext ({0})..
        /// </summary>
        public static string ErrorMsgLanguageTextProblemWhileCreatingLineInfos {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextProblemWhileCreatingLineInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During a PhraseList create operation with PhraseTextsCriteria, there was a problem when trying to fetch/create the languagetext ({0})..
        /// </summary>
        public static string ErrorMsgLanguageTextProblemWhileCreatingPhraseTexts {
            get {
                return ResourceManager.GetString("ErrorMsgLanguageTextProblemWhileCreatingPhraseTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data for username ({0})..
        /// </summary>
        public static string ErrorMsgLoadUserDataException {
            get {
                return ResourceManager.GetString("ErrorMsgLoadUserDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Ids were not found..
        /// </summary>
        public static string ErrorMsgMultipleIdsNotFoundException {
            get {
                return ResourceManager.GetString("ErrorMsgMultipleIdsNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current code must execute on the server only. Inner Exception (if any) message: {0}.
        /// </summary>
        public static string ErrorMsgMustRunOnServerException {
            get {
                return ResourceManager.GetString("ErrorMsgMustRunOnServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeedData threw an exception..
        /// </summary>
        public static string ErrorMsgSeedDataException {
            get {
                return ResourceManager.GetString("ErrorMsgSeedDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StudyData cannot be found for current user with username ({0})..
        /// </summary>
        public static string ErrorMsgStudyDataNotFoundForUserException {
            get {
                return ResourceManager.GetString("ErrorMsgStudyDataNotFoundForUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Update operation failed..
        /// </summary>
        public static string ErrorMsgUpdateFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgUpdateFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username ({0}) already exists..
        /// </summary>
        public static string ErrorMsgUsernameAlreadyExistsException {
            get {
                return ResourceManager.GetString("ErrorMsgUsernameAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username ({0}) does not match the UserId ({1}) in the database..
        /// </summary>
        public static string ErrorMsgUsernameAndUserIdDoNotMatchException {
            get {
                return ResourceManager.GetString("ErrorMsgUsernameAndUserIdDoNotMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username ({0}) was not found..
        /// </summary>
        public static string ErrorMsgUsernameNotFoundException {
            get {
                return ResourceManager.GetString("ErrorMsgUsernameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user has not been authenticated..
        /// </summary>
        public static string ErrorMsgUserNotAuthenticatedException {
            get {
                return ResourceManager.GetString("ErrorMsgUserNotAuthenticatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not authorized to perform this operation..
        /// </summary>
        public static string ErrorMsgUserNotAuthorizedException {
            get {
                return ResourceManager.GetString("ErrorMsgUserNotAuthorizedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user is not authorized, but attempted to do, the following: \n {0}.
        /// </summary>
        public static string ErrorMsgUserNotAuthorizedToDoException {
            get {
                return ResourceManager.GetString("ErrorMsgUserNotAuthorizedToDoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying the user ({0}) threw an exception..
        /// </summary>
        public static string ErrorMsgVerifyUserFailedException {
            get {
                return ResourceManager.GetString("ErrorMsgVerifyUserFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened that was very bad. Detail = {0}.
        /// </summary>
        public static string ErrorMsgVeryBadException {
            get {
                return ResourceManager.GetString("ErrorMsgVeryBadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max number of retries due to db deadlock has been attempted..
        /// </summary>
        public static string ErrorMsgVeryBadExceptionDetail_DeadlockRetriesExceededMaxTries {
            get {
                return ResourceManager.GetString("ErrorMsgVeryBadExceptionDetail_DeadlockRetriesExceededMaxTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result count was anticipated to be either one or zero.  This probably occurred when making a call to the database, expecting a unique result set..
        /// </summary>
        public static string ErrorMsgVeryBadExceptionDetail_ResultCountNotOneOrZero {
            get {
                return ResourceManager.GetString("ErrorMsgVeryBadExceptionDetail_ResultCountNotOneOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99999.
        /// </summary>
        public static string MaxSaltValue {
            get {
                return ResourceManager.GetString("MaxSaltValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string MaxTriesGenerateSalt {
            get {
                return ResourceManager.GetString("MaxTriesGenerateSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string MinLinesPerMultiLineText {
            get {
                return ResourceManager.GetString("MinLinesPerMultiLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string MinPhrasesPerTranslation {
            get {
                return ResourceManager.GetString("MinPhrasesPerTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase_DalKey.
        /// </summary>
        public static string Phrase_DalKey {
            get {
                return ResourceManager.GetString("Phrase_DalKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:50094/SlPortal.svc.
        /// </summary>
        public static string WcfProxyDefaultUrl {
            get {
                return ResourceManager.GetString("WcfProxyDefaultUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://kroker.azurewebsites.net/SlPortal.svc.
        /// </summary>
        public static string WcfProxyReleaseUrl {
            get {
                return ResourceManager.GetString("WcfProxyReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://kroker.azurewebsites.net/SlPortal.svc.
        /// </summary>
        public static string WcfProxyStagingUrl {
            get {
                return ResourceManager.GetString("WcfProxyStagingUrl", resourceCulture);
            }
        }
    }
}
